# Generated by Django 4.2.2 on 2023-10-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=12)),
                ('sites', models.CharField(max_length=50)),
                ('msg', models.CharField(max_length=50)),
            ],
        ),
    ]
